### ISSUE TITLE
i2c conf needs to be zero initialized

### ISSUE THREAD

**Issue by KWolfe81** [ys-oh/vl53l0x_esp32#2]
https://github.com/ys-oh/vl53l0x_esp32/blob/87b2c06b8ee5192e10c41838ab62b3dad3df7e53/platform/esp32/src/vl53l0x_i2c_platform.c#L59

Should be: `i2c_config_t conf = { 0 };` otherwise I get invalid i2c conf errors.

**Comment by ys-oh** [comment]
merged this issue in #3
